### ISSUE TITLE
Enter Button should onClick Add Friend

### ISSUE THREAD

**Issue by leftover19** [ericanderson2/leet-friends#4]
It would be a good functionality if pressing enter button will add the username.

**Comment by leftover19** [comment]
I can raise a PR if issue is acceptable

**Comment by ericanderson2** [comment]
That sounds like a good feature, I can include it in the next maintenance update I do (need to tweak some visuals and clean up the code anyways, maybe in the next week or so). 

Since the project is fairly small scale and basically complete as is, I don't really want to bother with reviewing PRs. I can do the implementation.

**Comment by ericanderson2** [comment]
Added in version 1.9
